DBCC CHECKIDENT (DesignerContest, RESEED, 0)
DBCC CHECKIDENT (DetailPictureContest, RESEED, 0)
DBCC CHECKIDENT (DetailPicturesDesign, RESEED, 0)
DBCC CHECKIDENT (ExamToBeDesigner, RESEED, 0)
DBCC CHECKIDENT (PicturesReference, RESEED, 0)
DBCC CHECKIDENT (UserRole, RESEED, 0)

EXEC sp_MSForEachTable 'DISABLE TRIGGER ALL ON ?'
GO
EXEC sp_MSForEachTable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL'
GO
EXEC sp_MSForEachTable 'DELETE FROM ?'
GO
EXEC sp_MSForEachTable 'ALTER TABLE ? CHECK CONSTRAINT ALL'
GO
EXEC sp_MSForEachTable 'ENABLE TRIGGER ALL ON ?'
GO